packages: ["i18n-error-base", "website"]
blockExoticSubdeps: true
ignoredBuiltDependencies: []
  # - esbuild
  # - sharp
minimumReleaseAge: 10080
minimumReleaseAgeExclude: []
onlyBuiltDependencies: []
strictDepBuilds: true
trustPolicy: no-downgrade
trustPolicyExclude: []
